[project]
name = "sindri"
version = "0.1.0"
description = "sindri (science routines) package"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "jormungandr",
  "bifrost",
  "vegtamr",
]

[tool.uv.sources]
jormungandr = { path = "jormungandr" }
bifrost = { path = "bifrost" }
vegtamr = { path = "vegtamr" }

