name = "PowerSpectra"
uuid = "51dcd213-da3c-4223-94ec-9c422af09901"
authors = ["Neco Kriel <necokriel@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
FFTW = "1.8.1"
